import { chromium } from "playwright-core";
const b = await chromium.launch({ channel: "chrome", headless: true });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto("http://localhost:8753/index.html", { waitUntil: "networkidle" });
await p.evaluate(() => document.querySelector("#generator").scrollIntoView({ behavior: "instant" }));
await p.waitForTimeout(600);
const before = await p.evaluate(() => { const g = document.querySelector("#glass"), cs = getComputedStyle(g); return { l: cs.left, t: cs.top, scrollY: scrollY }; });
const g = await p.$("#glass"); const bb = await g.boundingBox();
await p.mouse.move(bb.x + bb.width / 2, bb.y + bb.height / 2);
await p.mouse.down();
await p.mouse.move(bb.x + bb.width / 2 + 80, bb.y + bb.height / 2 + 40, { steps: 5 });
await p.mouse.up();
const after = await p.evaluate(() => { const g = document.querySelector("#glass"), cs = getComputedStyle(g); return { l: cs.left, t: cs.top, scrollY: scrollY }; });
console.log("before:", JSON.stringify(before), "\nafter: ", JSON.stringify(after));
console.log("delta:", parseFloat(after.l) - parseFloat(before.l), parseFloat(after.t) - parseFloat(before.t), "(expect 80 40)");
await b.close();
