import { chromium } from "playwright-core";
const b = await chromium.launch({ channel: "chrome", headless: true });
const p = await b.newPage({ viewport: { width: 1300, height: 800 }, deviceScaleFactor: 1.5 });
await p.goto("http://localhost:8753/index.html?v="+Date.now(), { waitUntil: "networkidle" });
await p.waitForTimeout(400);
await p.evaluate(() => document.querySelector("main").scrollIntoView());
await p.evaluate(() => window.scrollBy(0, 420));
await p.waitForTimeout(250);
await p.screenshot({ path: "bench/sticky.png" });
await b.close();
