import { chromium } from "playwright-core";
const b = await chromium.launch({ channel: "chrome", headless: true });
const p = await b.newPage({ viewport: { width: 1200, height: 700 }, deviceScaleFactor: 2 });
const errs=[]; p.on("console",m=>{ if(m.type()==="error") errs.push(m.text()); });
p.on("pageerror",e=>errs.push("PAGEERR: "+e.message));
await p.goto("http://localhost:8753/video-test.html?v="+Date.now(), { waitUntil: "networkidle" });
await p.waitForTimeout(1200);
await p.screenshot({ path: "bench/vt-floating-text.png" });
console.log("console errors:", errs.length ? errs : "none");
await b.close();
